const ranking = [
  "Fleet",
  "Gunnery",
  "Major",
  "Lance",
  "Warrant",
  "General",
  "Admiral",
  "Colonel",
  "Major",
  "Captain",
  "Ensign",
  "Officer",
  "Sergeant",
  "Corporal",
  "Private",
  "Airman",
  "Seaman",
  "Senior",
  "Staff",
  "Sheriff",
  "Manager",
  "Spy",
  "Agent",
  "Intern",
  "God",
  "Supreme",
  "Divine",
  "Daedric",
  "Undying",
  "Arch",
  "Exalted",
  "Master",
  "Elite",
  "Novice",
  "Emperor",
  "Führer",
  "King",
  "Queen",
  "Prince",
  "Duke",
  "Duchess",
  "Knight",
  "Legate",
  "Tribune",
  "Consul",
  "Baron",
  "Warlock",
  "Evoker",
  "Wizard",
  "Mage",
  "Orc",
];

const cupcake = [
  "Pie icing topping pudding cake cake pastry gummi bears apple pie. Muffin shortbread powder cotton candy marzipan sugar plum. Cake marzipan ice cream chupa chups soufflé topping.",
  "Cake jujubes sugar plum sweet fruitcake candy brownie. Soufflé pudding cake lemon drops oat cake tart pudding cotton candy chocolate bar. Oat cake ice cream danish cotton candy pudding. Croissant carrot cake cupcake donut caramels croissant cake dessert.",
  "Brownie icing lollipop lollipop jelly. Wafer caramels muffin shortbread brownie. Pastry sugar plum apple pie danish chocolate bar marzipan chocolate bar topping.",
  "Chocolate bar chocolate cake candy canes chocolate cake gingerbread tart cheesecake candy. Cake caramels tart gummi bears sugar plum liquorice candy canes bear claw sweet. Tiramisu pie candy gummies topping.",
  "Dessert danish oat cake tart chupa chups gingerbread apple pie halvah. Chupa chups dessert bear claw jelly jelly sesame snaps. Chocolate cake chupa chups marshmallow sugar plum powder marzipan tiramisu pudding.",
  "Cake chocolate bar wafer gingerbread icing cake. Powder jelly-o caramels chocolate bar oat cake chocolate. Croissant lollipop gingerbread oat cake pastry halvah dragée. Fruitcake jujubes pie halvah apple pie gummies cake.",
  "Wafer sweet roll dessert halvah jelly beans cake. Gummi bears jelly-o bonbon tootsie roll chocolate pastry macaroon pastry. Fruitcake apple pie carrot cake croissant apple pie marshmallow lemon drops icing. Cheesecake bear claw lemon drops pie dessert topping cotton candy soufflé.",
  "Tiramisu sweet roll cupcake ice cream danish sesame snaps jelly gingerbread. Cheesecake fruitcake apple pie macaroon biscuit halvah. Tiramisu sweet carrot cake dessert biscuit soufflé cupcake bear claw.",
  "Wafer gummies chupa chups chocolate bar jelly. Powder pastry cupcake marzipan lollipop. Candy wafer cupcake bonbon marshmallow jelly pudding pie.",
  "Sweet roll cheesecake cake jelly liquorice pastry bonbon jelly-o dragée. Bonbon sesame snaps liquorice cake chocolate cake sweet roll pie. Bonbon bonbon cake cake dessert macaroon.",
  "Candy pastry cotton candy halvah brownie marzipan topping marshmallow. Bear claw cookie brownie sweet roll donut candy. Pastry candy canes soufflé donut chupa chups. Jelly-o cookie tiramisu sugar plum powder carrot cake gummies sesame snaps pie.",
  "Fruitcake carrot cake carrot cake marzipan jujubes. Pastry jujubes liquorice lemon drops cotton candy. Shortbread pudding shortbread gummi bears chocolate donut marshmallow.",
  "Cotton candy bonbon bonbon croissant lemon drops. Jelly-o sweet pastry sesame snaps sweet jelly-o tootsie roll sugar plum jelly-o. Candy marshmallow wafer gingerbread gingerbread.",
  "Sugar plum donut cake macaroon apple pie oat cake pie. Brownie apple pie jelly beans chupa chups macaroon jelly beans pastry. Jelly beans cake jelly beans jelly-o tiramisu halvah halvah muffin. Tart candy caramels jelly biscuit pastry oat cake.",
  "Bonbon cotton candy candy caramels gummi bears shortbread toffee chocolate cake. Chocolate biscuit candy canes oat cake liquorice. Macaroon marzipan gingerbread tart bonbon. Jelly beans croissant cotton candy muffin chocolate.",
  "Chocolate bar jujubes pie soufflé caramels macaroon cookie. Liquorice dragée tart dessert macaroon. Sweet jujubes danish ice cream sweet roll candy jelly-o jelly-o halvah. Pastry sweet topping sesame snaps ice cream topping topping cake.",
  "Biscuit cake carrot cake cake dragée. Powder cheesecake lollipop cake jelly beans jujubes sesame snaps topping. Powder icing croissant jujubes wafer.",
  " Dessert ice cream dragée dessert marshmallow cupcake muffin icing sweet. Halvah carrot cake muffin candy canes pudding halvah ice cream. Jelly-o chocolate bar wafer bear claw chocolate bar. Jelly beans cupcake icing jelly beans soufflé.",
  "Pie jelly sweet chocolate cake chocolate bar chupa chups carrot cake. Gingerbread muffin toffee donut fruitcake cookie. Caramels bonbon brownie biscuit wafer soufflé. Pie bonbon fruitcake oat cake tart pastry tart.",
  "Lollipop dessert fruitcake muffin donut donut. Cupcake chocolate cake marzipan oat cake soufflé shortbread lemon drops chocolate tart. Pie soufflé tootsie roll macaroon chocolate bar.",
  "Danish apple pie gummies sesame snaps donut. Apple pie wafer pudding marzipan cheesecake sweet cupcake tart. Caramels toffee donut fruitcake pudding bear claw donut.",
  "Pudding chocolate cake sweet roll tart toffee gummies. Shortbread tiramisu bonbon muffin donut. Chupa chups jujubes toffee pastry cheesecake sweet roll bear claw cake.",
  "Icing donut jelly cupcake apple pie bear claw caramels dragée. Macaroon chupa chups jelly-o sweet caramels sweet. Shortbread powder bear claw dragée carrot cake chocolate bar.",
  "Cheesecake croissant dragée oat cake apple pie powder. Tootsie roll lollipop powder soufflé brownie. Cake sesame snaps tiramisu tart sweet pie carrot cake.",
  "Chocolate cake sweet donut bear claw caramels wafer. Sweet sugar plum soufflé candy canes liquorice. Croissant sweet shortbread tart topping dessert sesame snaps chocolate.",
];

const primary = [
  "slate",
  "gray",
  "zinc",
  "neutral",
  "stone",
  "red",
  "orange",
  "amber",
  "yellow",
  "lime",
  "green",
  "emerald",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "pink",
  "rose",
];

const names = [
  "Clayborne Poag",
  "Goldi Keaveney",
  "Richy Le Estut",
  "Luce Baynom",
  "Aldon Skett",
  "Izzy Ternault",
  "Maurits Beaves",
  "Lonnard Orfeur",
  "Lotty Kirkby",
  "Amandy O'Hern",
  "Shea Eslie",
  "Virge Jakoviljevic",
  "Millard Macer",
  "Bevon Mintoft",
  "Ryun Guitton",
  "Pearce Ramas",
  "Reider Gorey",
  "Teador Barnhart",
  "Burk Lembrick",
  "Jillana Shovelbottom",
  "Genni Tolotti",
  "Jolie Maxwaile",
  "Mignon Shawley",
  "Darla MacNalley",
  "Jerrine Billiard",
  "Meade Braithwaite",
  "Ezri Ferrarini",
  "Rana Cordsen",
  "Roxine Jakubowsky",
  "Dani Frampton",
  "Neill Paladino",
  "Tobie Cordon",
  "Martino Wharin",
  "Heall Gabala",
  "Anatollo O'Grady",
  "Jasper Grzelewski",
  "Angelique Benz",
  "Park Kettow",
  "Van Hartup",
  "Lebbie Bawdon",
  "Tamara Brattell",
  "Luisa Evensden",
  "Adriane Khristyukhin",
  "Dar Espinoy",
  "Opalina Priddle",
  "Arlie Mutton",
  "Christel Tie",
  "Rochester Pappin",
  "Hayden Haugg",
  "Ninette Leyland",
  "Menard Lyall",
  "Man Durak",
  "Valeria Garett",
  "Alvira O'Hagan",
  "Domini Rockingham",
  "Ealasaid Piggin",
  "Gasparo Treece",
  "Morgen Yendall",
  "Aileen Gubbins",
  "Shea Craigg",
  "Lilli Noonan",
  "Gene Eydel",
  "Aili Duinbleton",
  "Dell Bellham",
  "Wood Mebes",
  "Dar Durn",
  "Britta Denley",
  "Cilka Sworne",
  "Toma Danielovitch",
  "Gabriel Bagnold",
  "Verena Mechi",
  "Darcey Mepham",
  "Wendie MacSorley",
  "Belita Korb",
  "Codie Tearny",
  "Marga Folli",
  "Ermina Knoles",
  "Josephine Sander",
  "Svend Pavia",
  "Frankie Myrkus",
  "Deerdre Blincko",
  "Duky MacGown",
  "Verla Melbourn",
  "Doralyn Blaycock",
  "Emmott Michiel",
  "Marcy Tebbett",
  "Odelia Lanfranchi",
  "Olympia MacWhirter",
  "Anderson Ezzell",
  "Loren Rattry",
  "Vassily Dowry",
  "Alvinia Qualtro",
  "Maurizio Crat",
  "Mile Ilyuchyov",
  "Florie Weeks",
  "Woodman Asquith",
  "Geralda Tipler",
  "Christos Southam",
  "Marcelo Hugueville",
  "Gasper Niland",
  "Jillane Thynne",
  "Issy Farragher",
  "Lisabeth Murrock",
  "Carilyn Cockshutt",
  "Miltie Wyrill",
  "Marleah Boniface",
  "Evvy Hayne",
  "Otes Coppenhall",
  "Valli Chugg",
  "Delainey Crust",
  "Cyndia McNirlan",
  "Garrik Aggett",
  "Roxana Hyndson",
  "Lil Martinello",
  "Helene McGilben",
  "Joshuah MacDermot",
  "Bevan Pursey",
  "Roderigo Maffey",
  "Dorie Vergo",
  "Hy Sibun",
  "Angelika Ferres",
  "Bord Debow",
  "Husein Speddin",
  "Ulrick Van den Hof",
  "Wainwright Armell",
  "Ofelia Basnall",
  "Creight Bycraft",
  "Shaine Zambonini",
  "Kristel Keller",
  "Maddy Le Moucheux",
  "Sean Windybank",
  "Kaylil Kinsett",
  "Dehlia Duffus",
  "Alyosha Lantiff",
  "Rena McAughtry",
  "Edlin Sandry",
  "Issie Pantone",
  "Stillmann Weldrick",
  "Ashly Reidshaw",
  "Karil Sicha",
  "Tedie Butlin",
  "Grier Anelay",
  "Anabal Gobert",
  "Mortimer Embling",
  "Josselyn McGuiness",
  "Annetta Bingley",
  "Marie-ann Sheavills",
  "Gloria Whittington",
  "Ardis MacParland",
  "Joelynn Pimblott",
  "Rochelle Absolon",
  "Eimile De Bruyn",
  "Bryan Teissier",
  "Bianca Carr",
  "Gregg Jarrett",
  "Barron Saffell",
  "Milly Mingay",
  "Bab Vanezis",
  "Nappy A'Barrow",
  "Roderich Bruster",
  "Liv Sylett",
  "Brit Hembrow",
  "Clevie Evanson",
  "Bellanca Weins",
  "Vita Wyldbore",
  "Daisey Luscott",
  "Lewie Cowden",
  "Eulalie Piddick",
  "Grove Kimmings",
  "Shurwood Yitshak",
  "Rutter Cocksedge",
  "Sidney Thay",
  "Quinn Groome",
  "Shirlee Sturton",
  "Blaire Leglise",
  "Erick Nelm",
  "Russ Estcot",
  "Jodie Fant",
  "Netty Isakovic",
  "Teresa Mallows",
  "Kerrill Baldacchino",
  "Adolphus Minshaw",
  "Lena Cocking",
  "Winn Iddiens",
  "Gerhardine Fawdrie",
  "Tammie Brogden",
  "Ainslie Attard",
  "Alissa Petruska",
  "Armando Middlemist",
  "Gae O'Shiels",
  "Matty Fransinelli",
  "Guillema Dobrovolski",
  "Rolland Latham",
  "Wendell Powlesland",
  "Liz Kohtler",
  "Marga Pithcock",
  "Mireille Roggers",
  "Miguel Franzotto",
  "Raynell Dolman",
  "Moria Tedorenko",
];
